//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyota.Tsusho.API.Testing.OrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmationDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/order")]
    [System.SerializableAttribute()]
    public partial class ConfirmationDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private int PlantField;
        
        private int UnitsField;
        
        private System.DateTime ProducedField;
        
        private string SuffixField;
        
        private Toyota.Tsusho.API.Testing.OrderServiceReference.ColorDataContract ColorField;
        
        private string CategoryField;
        
        private Toyota.Tsusho.API.Testing.OrderServiceReference.PurchaserDataContract PurchaserField;
        
        private string VendorField;
        
        private System.DateTime DeliveryField;
        
        private string OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Plant {
            get {
                return this.PlantField;
            }
            set {
                if ((this.PlantField.Equals(value) != true)) {
                    this.PlantField = value;
                    this.RaisePropertyChanged("Plant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((this.UnitsField.Equals(value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Produced {
            get {
                return this.ProducedField;
            }
            set {
                if ((this.ProducedField.Equals(value) != true)) {
                    this.ProducedField = value;
                    this.RaisePropertyChanged("Produced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public Toyota.Tsusho.API.Testing.OrderServiceReference.ColorDataContract Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public Toyota.Tsusho.API.Testing.OrderServiceReference.PurchaserDataContract Purchaser {
            get {
                return this.PurchaserField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaserField, value) != true)) {
                    this.PurchaserField = value;
                    this.RaisePropertyChanged("Purchaser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime Delivery {
            get {
                return this.DeliveryField;
            }
            set {
                if ((this.DeliveryField.Equals(value) != true)) {
                    this.DeliveryField = value;
                    this.RaisePropertyChanged("Delivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/order")]
    [System.SerializableAttribute()]
    public partial class ColorDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InternalField;
        
        private string ExternalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Internal {
            get {
                return this.InternalField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalField, value) != true)) {
                    this.InternalField = value;
                    this.RaisePropertyChanged("Internal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string External {
            get {
                return this.ExternalField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalField, value) != true)) {
                    this.ExternalField = value;
                    this.RaisePropertyChanged("External");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaserDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/order")]
    [System.SerializableAttribute()]
    public partial class PurchaserDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GroupField;
        
        private string OrganizationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ttaf.co.za/talo/api/2014/05", ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        // CODEGEN: Generating message contract since the wrapper name (OrderConfirmationRequestMessage) of message OrderConfirmationRequestMessage does not match the default value (Confirm)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ttaf.co.za/talo/api/2014/05/IOrderService/Confirm")]
        void Confirm(Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ttaf.co.za/talo/api/2014/05/IOrderService/Confirm")]
        System.Threading.Tasks.Task ConfirmAsync(Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderConfirmationRequestMessage", WrapperNamespace="http://www.ttaf.co.za/talo/api/2014/05", IsWrapped=true)]
    public partial class OrderConfirmationRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ttaf.co.za/talo/api/2014/05/order", Order=0)]
        public Toyota.Tsusho.API.Testing.OrderServiceReference.ConfirmationDataContract Confirmation;
        
        public OrderConfirmationRequestMessage() {
        }
        
        public OrderConfirmationRequestMessage(Toyota.Tsusho.API.Testing.OrderServiceReference.ConfirmationDataContract Confirmation) {
            this.Confirmation = Confirmation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService>, Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService.Confirm(Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage request) {
            base.Channel.Confirm(request);
        }
        
        public void Confirm(Toyota.Tsusho.API.Testing.OrderServiceReference.ConfirmationDataContract Confirmation) {
            Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage inValue = new Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage();
            inValue.Confirmation = Confirmation;
            ((Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService)(this)).Confirm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService.ConfirmAsync(Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage request) {
            return base.Channel.ConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task ConfirmAsync(Toyota.Tsusho.API.Testing.OrderServiceReference.ConfirmationDataContract Confirmation) {
            Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage inValue = new Toyota.Tsusho.API.Testing.OrderServiceReference.OrderConfirmationRequestMessage();
            inValue.Confirmation = Confirmation;
            return ((Toyota.Tsusho.API.Testing.OrderServiceReference.IOrderService)(this)).ConfirmAsync(inValue);
        }
    }
}
