//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toyota.Tsusho.API.Testing.ShippingInformationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ShippingInformationCollectionDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation", ItemName="ShippingInformation")]
    [System.SerializableAttribute()]
    public class ShippingInformationCollectionDataContract : System.Collections.Generic.List<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationDataContract> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingInformationDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation")]
    [System.SerializableAttribute()]
    public partial class ShippingInformationDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string VehicleNumberField;
        
        private string StoreField;
        
        private System.DateTime DocumentedField;
        
        private System.DateTime PostedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryNoteField;
        
        private string BillofLadingField;
        
        private Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.InvoiceReferenceDataContract InvoiceField;
        
        private Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.VehicleReferenceCollectionDataContract VehiclesField;
        
        private Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ModificationEnumeration ModificationField;
        
        private System.DateTime ModifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string VehicleNumber {
            get {
                return this.VehicleNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNumberField, value) != true)) {
                    this.VehicleNumberField = value;
                    this.RaisePropertyChanged("VehicleNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Documented {
            get {
                return this.DocumentedField;
            }
            set {
                if ((this.DocumentedField.Equals(value) != true)) {
                    this.DocumentedField = value;
                    this.RaisePropertyChanged("Documented");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Posted {
            get {
                return this.PostedField;
            }
            set {
                if ((this.PostedField.Equals(value) != true)) {
                    this.PostedField = value;
                    this.RaisePropertyChanged("Posted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DeliveryNote {
            get {
                return this.DeliveryNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryNoteField, value) != true)) {
                    this.DeliveryNoteField = value;
                    this.RaisePropertyChanged("DeliveryNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string BillofLading {
            get {
                return this.BillofLadingField;
            }
            set {
                if ((object.ReferenceEquals(this.BillofLadingField, value) != true)) {
                    this.BillofLadingField = value;
                    this.RaisePropertyChanged("BillofLading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.InvoiceReferenceDataContract Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.VehicleReferenceCollectionDataContract Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ModificationEnumeration Modification {
            get {
                return this.ModificationField;
            }
            set {
                if ((this.ModificationField.Equals(value) != true)) {
                    this.ModificationField = value;
                    this.RaisePropertyChanged("Modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceReferenceDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation")]
    [System.SerializableAttribute()]
    public partial class InvoiceReferenceDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumberField;
        
        private System.DateTime DateField;
        
        private decimal AmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="VehicleReferenceCollectionDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation", ItemName="Vehicle")]
    [System.SerializableAttribute()]
    public class VehicleReferenceCollectionDataContract : System.Collections.Generic.List<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.VehicleReferenceDataContract> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModificationEnumeration", Namespace="http://www.ttaf.co.za/talo/api/2014/05")]
    public enum ModificationEnumeration : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleReferenceDataContract", Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation")]
    [System.SerializableAttribute()]
    public partial class VehicleReferenceDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumberField;
        
        private string VINField;
        
        private string EngineField;
        
        private Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ModificationEnumeration ModificationField;
        
        private System.DateTime ModifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Engine {
            get {
                return this.EngineField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineField, value) != true)) {
                    this.EngineField = value;
                    this.RaisePropertyChanged("Engine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ModificationEnumeration Modification {
            get {
                return this.ModificationField;
            }
            set {
                if ((this.ModificationField.Equals(value) != true)) {
                    this.ModificationField = value;
                    this.RaisePropertyChanged("Modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ttaf.co.za/talo/api/2014/05", ConfigurationName="ShippingInformationServiceReference.IShippingInformationService")]
    public interface IShippingInformationService {
        
        // CODEGEN: Generating message contract since the operation Update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ttaf.co.za/talo/api/2014/05/IShippingInformationService/Update", ReplyAction="http://www.ttaf.co.za/talo/api/2014/05/IShippingInformationService/UpdateResponse" +
            "")]
        Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse Update(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ttaf.co.za/talo/api/2014/05/IShippingInformationService/Update", ReplyAction="http://www.ttaf.co.za/talo/api/2014/05/IShippingInformationService/UpdateResponse" +
            "")]
        System.Threading.Tasks.Task<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse> UpdateAsync(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShippingInformationUpdateRequestMessage", WrapperNamespace="http://www.ttaf.co.za/talo/api/2014/05", IsWrapped=true)]
    public partial class ShippingInformationUpdateRequestMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ttaf.co.za/talo/api/2014/05/shippinginformation", Order=0)]
        public Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationCollectionDataContract Shippings;
        
        public ShippingInformationUpdateRequestMessage() {
        }
        
        public ShippingInformationUpdateRequestMessage(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationCollectionDataContract Shippings) {
            this.Shippings = Shippings;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        public UpdateResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingInformationServiceChannel : Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingInformationServiceClient : System.ServiceModel.ClientBase<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService>, Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService {
        
        public ShippingInformationServiceClient() {
        }
        
        public ShippingInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService.Update(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage request) {
            return base.Channel.Update(request);
        }
        
        public void Update(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationCollectionDataContract Shippings) {
            Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage inValue = new Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage();
            inValue.Shippings = Shippings;
            Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse retVal = ((Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse> Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService.UpdateAsync(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.UpdateResponse> UpdateAsync(Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationCollectionDataContract Shippings) {
            Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage inValue = new Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.ShippingInformationUpdateRequestMessage();
            inValue.Shippings = Shippings;
            return ((Toyota.Tsusho.API.Testing.ShippingInformationServiceReference.IShippingInformationService)(this)).UpdateAsync(inValue);
        }
    }
}
